### ISSUE TITLE
struggling to mock

### ISSUE THREAD

**Issue by yvz5** [theKashey/rewiremock#100]
hi there,

i am totally newbie in javascript unit testing world. Came across this package and wanted to test my module which has a dependency on kafka-node and uuid. But I couldnt figure out how to mock kafka classes and the uuid. 

Could you look at the following code ? It gives an error that it can not find uuid.
app.js
```js
const uuid = require('uuid/v4');
const kafka = require('kafka-node');

// TODO: use an env variable for the kafka url
const kafkaClient = new kafka.KafkaClient({ kafkaHost: 'kafka.kubeless:9092' });
const kafkaProducer = new kafka.Producer(kafkaClient);
const kafkaTopicToSend = 'data-arrived';

module.exports = {
    app: function (event, context) {
        return new Promise((resolve, reject) => {
            // check if incoming data is valid
            this.validate(event.data, reject);
                                                
            resolve({
                id: uuid(),
                created_at: new Date(),
                data: event.data
            });
        }).then((data) => {
            return new Promise((resolve, reject) => {                
                kafkaProducer.send([{
                    topic: kafkaTopicToSend,
                    messages: JSON.stringify(data),
                    partition: 0
                }],
                (err, data) => {
                    if (err) {
                        reject(err);
                    } else {
                        resolve(data);
                    }
                });
            });
        }).then((data) => {
            event.extensions.response.statusCode = 200;
            return data;
        }).catch((err) => {
            event.extensions.response.statusCode = 400;
            return err;
        });
    },

    validate: function(data, reject) {
        if (!data) {
            reject('Missing field: data');
        }        
    }
}
```
app.test.js
```js
const rewiremock = require('rewiremock').default;

describe('app', function() {  
  
  rewiremock(() => require('kafka-node'))  
    .with({
      send: function(cb) {
        return cb.data;
      }
    })
    .calledFromMock();

  rewiremock(() => require('uuid'))  
    .with({
      hello: function () {
        return 'hello';
      }
    })
    .calledFromMock();

  beforeEach( () => rewiremock.enable() );

  const app = require('../app.js');  

  it('rejects when data field is missing', async function() {
    const event = {data: {hello: "World"}};

    const result = await app.app(event, {});

    expect(result).to.equal('data');
  });

  afterEach( () => rewiremock.disable() );
});
```

error: 
```
npm test

> restapi@0.0.1 test C:\x
> mocha

C:\x\node_modules\yargs\yargs.js:1163
      else throw err
           ^

Error: Cannot find module 'uuid/v4'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
```

**Comment by theKashey** [comment]
I am not sure why this example is not working (as long as you are not mocking `uuid/v4`), but it would not work in any case.
- what shall be mocked here?
```rewiremock(() => require('kafka-node'))  
    .with({
      send: function(cb) {
        return cb.data;
      }
    })
```
After this operation `require('kafka-node')` would return `send` and only it. And there is no way you can mock the whole kafka.

- and here?
```js
rewiremock(() => require('uuid'))  
    .with({
      hello: function () {
        return 'hello';
      }
    })
    .calledFromMock();
```
Probably it should be `uuid/v4`, and not `hello`.

How to fix?
- try to move initialization to another file
```js
const kafkaClient = new kafka.KafkaClient({ kafkaHost: 'kafka.kubeless:9092' });
const kafkaProducer = new kafka.Producer(kafkaClient);

exports.send = (cb) => kafkaProducer.send(cb);
```
Now you can mock `send`, but it would not work great if you need use multiple instances.

- try to isolate "actions" in functions or method, and then "inherit" from it
```js
const app = {
  app: ....
  _send: ....
}
class TestApp extends app {
  _send: yourTestImplementationOfTest
}
```
then - test `TestApp`.

Look like the only way to test,  is to make your code more testable.

**Comment by yvz5** [comment]
its not possible to use any classes as I am using kubeless ( only functions ). So my question is, how would I go about mocking kafka ? 

how would I mock the following ? 
```
const kafkaClient = new kafka.KafkaClient({ kafkaHost: 'kafka.kubeless:9092' });
const kafkaProducer = new kafka.Producer(kafkaClient);
```

because I need to send a message to the kafka topic, I need the dependency.

Another dependency is uuid/v4. I wanted to mock the uuid() function.

Am I trying to do something thats not possible ? I've read that you can mock the whole module, so thats why I tried to mock kafka uuid. Otherwise I need to create a proxy function and test only that. But that requires code change.  Is it possible ?

**Comment by theKashey** [comment]
You __cannot__ mock the whole `kafka` - you will have to mock `kafka.KafkaClient` you are using, as well as `kafka.Producer` - it's a too complex thing. And not like "mock"(replace my nothing) - actually, provide some sound implementation which will do what you need.
But if you will move this initialization to another file, which will export a _simpler_ API - then it would be possible to mock whatever you need.

In the same time - mocking `uuid` is not a problem - just mock it.
```js
rewiremock(() => require('uuid'))  
    .with(() =>'uuid🤞')
```

**Comment by yvz5** [comment]
I dont want to mock the whole kafka, I want to mock just the send method on the kafka.Producer. But that depends on the KafkaClient and has some constructor logic on it. I don't understand how that works though. can you show me a sample mocking for example the kafkaproducer ?

**Comment by yvz5** [comment]
I finally found a way to do this by using another mocking framework called sinon, if anyone is interested:

`let kafkaProducer = sinon.createStubInstance(kafka.Producer); `

**Comment by theKashey** [comment]
That's not another mocking framework, it's more about another mocking school. And it won't end well as any other "partial mocking" approach.
`createStubInstance` is creating a clone of an object, which does nothing. However - "when" it creates it, and "how" the stubbed version got used by the real code?
There are only two ways to do it
- via Dependency Injection, or module system(which is the same)
- via variable injections and overrides by any sorts, including the ones provided by sinon.
If you are going that way - [please, stop playing with XXX](https://dev.to/thekashey/please-stop-playing-with-proxyquire-11j4)
