### ISSUE TITLE
Rewiremock: there is no "parent module". Is there two HotModuleReplacementPlugins?

### ISSUE THREAD

**Issue by hyperh** [theKashey/rewiremock#106]
I'm using `rewiremock` with https://github.com/storybookjs/storybook.

I've mocked out some functions that contain side effects using `rewiremock`. This all works when I run a local Storybook. 

However, once I go to build a static Storybook website and go visit the page, I get the error:
`Rewiremock: there is no "parent module". Is there two HotModuleReplacementPlugins?` The static Storybook website uses `NODE_ENV=production` and [Webpack seems to say](https://webpack.js.org/plugins/hot-module-replacement-plugin/) not to use `HotModuleReplacementPlugin` in production

I checked my webpack config and there's no `HotModuleReplacementPlugin` at all.

**Comment by hyperh** [comment]
Actually I see that this issue is the same as #89

**Comment by theKashey** [comment]
Yeah, unfortunately the additional module information rewiremock needs for living comes from HotModuleReplacementPlugin.

**Comment by kruncher** [comment]
Does rewiremock require webpack and HotModuleReplacementPlugin in order to work?

I am not using webpack.

**Comment by theKashey** [comment]
`rewiremock` works in `webpack` or in `nodejs` environments, but not Jest

**Comment by kruncher** [comment]
I have the following at the top of my test file:

```js
import rewiremock from 'rewiremock/node';
```

But am seeing the following error:

> Uncaught Error: Rewiremock: there is no "parent module". Is there two HotModuleReplacementPlugins

If I move the import to here:

```js
before(async () => {
  await import('rewiremock/node');
});
```

Then I get an error saying that `rewiremock.disable` is undefined.
