### ISSUE TITLE
Mocking node implicit globals.

### ISSUE THREAD

**Issue by andreventuravale** [theKashey/rewiremock#107]
Hi, 
Is that possible to mock node implicit globals, e.g. the console instance.

I could not figure out from the documentation.

Regards,
André

**Comment by theKashey** [comment]
There are two ways to mock them:
- `global.console = something` or `sinon.spy(console,"log")`
- make that _implicit globals_ a `local` variable, by injecting some code to the beginning of every file.
> For Nodejs its better to use [Pirates](https://github.com/ariporad/pirates) — the library babel.js uses to “apply” es6-es5 transplation.

`rewiremock` is __only__ about dependencies and has nothing with both variants.
