### ISSUE TITLE
How to mock @reach/router navigate

### ISSUE THREAD

**Issue by thoughtassassin** [theKashey/rewiremock#109]
I am trying to mock Reach Router's navigate in a Storybook component that I am using. I would think something like this would work:

`rewiremock.module(() => import("@reach/router"), {
  navigate: { navigate: () => "" },
});`

where I usually import and use the module in my app like:

`import {navigate} from '@reach/router'`

This doesn't seem to be working. Is there another way to mock a module with named exports?

**Comment by theKashey** [comment]
keep in mind - you cannot use __async__ mock for the __sync__ and static import.
try
```js
rewiremock.proxy(() => require("@reach/router"), { navigate: { navigate: () => "" }, });
```
In this case the mock should be established before something would import `@reach/router` and it might work.
