### ISSUE TITLE
mockThroughByDefault plugin doesn't preserve classes

### ISSUE THREAD

**Issue by kataik** [theKashey/rewiremock#120]
Let's say I have a module I'd like to mock, which exports a class definition and a function as default:

```typescript
function foo(): string {
  return 'foo';
}

class Bar {
  public field: string = 'bar';
  public bar() {
    return 'bar';
  }
}

export default foo;
export { Bar };
```

When using the `mockThroughByDefault` plugin, it translates the exported class `Bar` into a constructor function which constructs an empty object. If I remove the plugin and call `callThrough()` directly, it works as expected:

```typescript
import rewiremock, { addPlugin, plugins } from 'rewiremock';
import * as dependency from './dependency';

addPlugin(plugins.mockThroughByDefault); // to make it work, comment this line

async function execute() {
  rewiremock(() => require('./dependency'))
    // .callThrough() // to make it work, uncomment this line
    .withDefault(() => 'mock');

  rewiremock.enable();
  const mod: typeof dependency = require('./dependency');
  rewiremock.disable();

  console.dir(mod);
  const bar = new mod.Bar();
  console.dir(bar);
  console.info(bar.field);
  console.info(bar.bar());
}

execute().then(() => console.info('done'));
```

Again, if I replace the plugin with `callThrough()`, it yields (as expected):

> { default: [Function], Bar: [Function: Bar] }
> Bar { field: 'foo' }
> foo
> foo
>  done

Test project: https://repl.it/repls/HeavyProfuseMaps

**Comment by theKashey** [comment]
Standard `mockFactory` creates empty functions. Just mocks.
You might need to use more smart something, like [sinon.spy](https://sinonjs.org/releases/latest/spies/) or [jest-mock](https://www.npmjs.com/package/jest-mock) - there is function to provide default implementation - [.stubFactory](https://github.com/theKashey/rewiremock/blob/153e93815018d0b24ed95252ff4256407a487942/README.md#helper-functions)

See example of usage -
https://github.com/theKashey/rewiremock/blob/b13cd4b19660b6cb4570919b27a27450c63e97b1/_tests/mock.spec.js#L359-L364

**Comment by kataik** [comment]
Thanks for the quick response. I actually did not expect it to define mocks/stubs for me, I do that separately. I was expecting it to implicitly add `.callThrough()` to all `.with(..)` and `.withDefault(..)` calls.

**Comment by theKashey** [comment]
Probably. There are 3 behaviors:
- do nothing. Use only what you provided via `.with`
- `callThrough'. Keep all methods original, except the ones you overridden via `.with`
- `mockThrough`. The same as above, but it "maps"(stubs) all `original` stuff via `stubsFactory`

The default mode is the first one - do nothing you haven't asked for explicitly.

**Comment by kataik** [comment]
My bad, thanks for explaining! Great library!
