### ISSUE TITLE
Testing a private function using rewiremock 

### ISSUE THREAD

**Issue by Saif-Shines** [theKashey/rewiremock#129]
There is a private function that is not exported by a module under test. 

I have been trying to solve this use rewire npm package. I am just wondering `rewiremock` could solve this problem?

[Example](https://medium.com/@macsikora/how-to-test-private-functions-of-es6-module-fb8c1345b25f)

**Comment by theKashey** [comment]
Absolutely unsupported, and should you not "want" to test a private function.
Just move it to another file and obtain full control over it. Do not _hack_ your own code.

Read more about the subj and examples - https://dev.to/thekashey/please-stop-playing-with-proxyquire-11j4

**Comment by Saif-Shines** [comment]
That helps. Thank you 😀
