### ISSUE TITLE
Support for mocking ES6 classes?

### ISSUE THREAD

**Issue by dennybaa** [theKashey/rewiremock#13]
```js
class Foo {
};
export default Foo; // not the default itself should be mocked but its instances
```

As I understand rewiremock works only with functions, i.e. I couldn't figure out how to mock classes. @theKashey Would you please provide some clues whether it's possible or not?

Thank you!

**Comment by theKashey** [comment]
JFYI - class IS a function. 
Anyway - rewiremock does not mock functions or classes - it mocks ‘names’. 
Also, there is no way to mock instances, but not mock class itself, as long you have to override constructor to produce different instances. 

‘’’js
Rewiremock(“file”).withDefault(MyMockedFoo);
‘’’

Anyway could you explain what are you actually trying to do.

**Comment by dennybaa** [comment]
> Also, there is no way to mock instances, but not mock class itself, as long you have to override constructor to produce different instances.

@theKashey Thank you, I understand. My question referred to instances solely... Basically mocking of instances is not required.
But it might be cool to have rewiremock detect a class (constructor) and hijack it with a stub factory function, what do you think? So that make the bellow possible? Is it an overkill?

```js
Rewiremock("./module-exporting-a-class")
  .es6()
  .callThrough()
  .with({
    overridded_method: () => 'stub'
  })
   
rewiremock.enable()

import MockedKlass from './module-exporting-a-class'
let mockedInstance = MockedKlass()
console.log(mockedInstance.overridded_method())

rewiremock.disable()
```
This could be more intuitive when using es6 classes. Otherwise the situation as like you say, rewiremock mocks names and expects them to be *functions*.

**Comment by dennybaa** [comment]
I'm looking into testdouble also, they seem to have for this need https://github.com/testdouble/testdouble.js#tdconstructor

**Comment by theKashey** [comment]
This is absolutely unrelated things. 
TD produces _stubs_, rewiremock _rewires_ your modules and could replace exports of some module by the _something_ you will provide.

Rewiremock is only about rewiring/mocking dependencies. To create fakes/doubles you have to use td or sinon.
Also keep in mind - td has build in support for mocking (td.replace).

**Comment by dennybaa** [comment]
@theKashey Thank you, for clarifications. Keep up, awesome library!
