### ISSUE TITLE
Does rewiremock work with ts-node?

### ISSUE THREAD

**Issue by justin-calleja** [theKashey/rewiremock#145]
I left a repo here with an example of failing to mock: https://github.com/justin-calleja/use-rewiremock

Can anyone point me in the right direction?

Thanks

**Comment by justin-calleja** [comment]
Closing issue as was missing:

```ts
rewiremock.enable()
```

and then it works. Added fix to example repo: https://github.com/justin-calleja/use-rewiremock/commit/53f78a3883bf4b65c5e859da0501d9228b21d189

**Comment by theKashey** [comment]
JFYI: https://github.com/justin-calleja/use-rewiremock/blob/main/src/tmp.ts should not work because all imports will be executed PRIOR any other code - they will be automatically hoisted as imports cannot happen in the middle of the file.

If you need _something_ like that - you have to add `rewiremock/babel`

**Comment by justin-calleja** [comment]
@theKashey thanks for taking the time to check this out!

> all imports will be executed PRIOR any other code - they will be automatically hoisted as imports cannot happen in the middle of the file.

hmm then must be `ts-node` that's allowing me to use `import`s in middle of file? Not sure, but it is working; both latest (made some small changes): https://github.com/justin-calleja/use-rewiremock/commit/ea80fd702fe884abd157c59544c4b000ae77a51f

and original: https://github.com/justin-calleja/use-rewiremock/commit/53f78a3883bf4b65c5e859da0501d9228b21d189

I'm running with:

```sh
❯ ./node_modules/.bin/ts-node ./src/tmp.ts
```

One thing I had to do (in another context / project) was to use full path like this:

```ts
rewiremock(resolve(__dirname, '../../src/path/to/file')).with(() => '... mocked response')
```

Without doing the full path - I'd have one import be mocked and another one (import of same module X from anther file - not mocked).
