### ISSUE TITLE
Testing a promise rejection with custom Error using chai-as-promise not work through rewiremock

### ISSUE THREAD

**Issue by reevolt** [theKashey/rewiremock#149]
I'm trying to test the Error custom type of a promise rejection using chai-as-promise through a mocked function with rewiremock. I'm not able to test the subtype of the Error when using rewiremock but the same test without mocking my function works well.

The example below illustrates the issue encountered:

MyController.ts
```ts
export class NotFoundError extends Error {
  constructor(message = "Not found") {
    super(message);
  }
}

export const myController = async (): Promise<void> => {
  throw new NotFoundError();
};
```

MyController.spec.ts
```ts
import { expect } from "chai";
import rewiremock from "rewiremock/node";

import { NotFoundError, myController } from "./MyController";

describe.only("myController", () => {
  it("should throw NotFoundError", async () => {
    await expect(myController()).to.eventually.rejectedWith(NotFoundError);
  });

  it("should throw NotFoundError through rewiremock", async () => {
    const { myController } = await rewiremock.module(() => import("./MyController"));
    await expect(myController()).to.eventually.rejectedWith(NotFoundError);
  });
});
```

The first not using rewiremock test passes, but the second using rewiremock not work as expected:

```sh
  myController
    ✔ should throw NotFoundError
    1) should throw NotFoundError through rewiremock


  1 passing (43ms)
  1 failing

  1) myController
       should throw NotFoundError through rewiremock:

      AssertionError: expected promise to be rejected with 'NotFoundError' but it was rejected with 'Error: Not found'
      + expected - actual

      -Error: Not found
      +NotFoundError
```

I'm using:
- rewiremock@3.14.5
- chai@4.3.4
- chai-as-promised@7.1.5
- mocha@9.2.2

Did I make a mistake? should I write my test in an other way or this is a real bug in rewiremock?

**Comment by theKashey** [comment]
You are running a situation where "two worlds" meet each other - the "real" and the "mocked"

You need to get not only mocked `myController`, but `NotFoundError` as well.
```tsx
const { myController, NotFoundError } = await rewiremock.module(() => import("./MyController"));
await expect(myController()).to.eventually.rejectedWith(NotFoundError);
```
Alternatively you can move `NotFoundError` to another file(re-export via MyController is ok), in this case mocking `MyController` will not cause it's "duplication"
