### ISSUE TITLE
webpack 4.2.0

### ISSUE THREAD

**Issue by BegeMode** [theKashey/rewiremock#21]
It is the awesome testing library, it very helped me to test vuex store. But I updated webpack to version 4 and getting now:

(node:15400) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:15400) DeprecationWarning: Compilation.moduleTemplate: Use Compilation.moduleTemplates.javascript instead

Thank you for this tool!

**Comment by theKashey** [comment]
Ok. I will have a look.
I've tested it with webpack 4.2.0 just a few weeks ago, and look like test those warnings, as long tests were green.

**Comment by dogoku** [comment]
Hi, just a heads up, the upcoming webpack 5 will remove all features deprecated in v4
https://github.com/webpack/changelog-v5/blob/master/README.md#removed-deprecated-items

**Comment by dogoku** [comment]
i think i have a PR for this (assuming i understood what webpack means)

**Comment by theKashey** [comment]
❤️

**Comment by theKashey** [comment]
Released as v3.13.4
