### ISSUE TITLE
How to mock promisified call to s3 with Typescript?

### ISSUE THREAD

**Issue by tommedema** [theKashey/rewiremock#37]
Consider the following file `index.ts`:

    import { S3 } from 'aws-sdk'
    import { promisify } from 'util'

    const s3 = new S3({ apiVersion: '2006-03-01' })
    const getObject = promisify<S3.GetObjectRequest, S3.GetObjectOutput>(
      () => s3.getObject // tslint:disable-line: no-unbound-method
    )

    /**
    * Describes a s3 object.
    */
    export interface IS3ObjectInfo {
      bucketArn: string
      objectKey: string
    }

    /**
    * Fetches an object from an s3 bucket.
    */
    export const fetchObjectFromS3 = async (
      objectInfo: IS3ObjectInfo
    ): Promise<Buffer> => {
      const { bucketArn, objectKey } = objectInfo

      const file = await getObject({
        Bucket: bucketArn,
        Key: objectKey
      })

      if (!Buffer.isBuffer(file.Body)) {
        throw new Error('file body is not a buffer')
      }

      return file.Body
    }

My objective is to mock the promisified createObject call. What I tried:

    // tslint:disable: no-implicit-dependencies no-magic-numbers no-console
    // tslint:disable: no-var-requires no-require-imports comment-format
    // tslint:disable: only-arrow-functions

    import { fetchObjectFromS3 } from '../src'
    import rewiremock from 'rewiremock'

    describe('serverless-diy-bucket', function(): void {
      this.timeout('30s')

      it.only('should fetch an object from s3 with from object info', async () => {
        rewiremock('aws-sdk/S3').with({
          getObject: (): void => {
            console.log('get object was called')
          }
        })

        rewiremock.enable()

        const file = await fetchObjectFromS3({
          bucketArn: 'arn:aws:s3:::myarn',
          objectKey: 'alpha/a-company/input/test.txt'
        })

        console.log(file)

        rewiremock.disable()
      })
    })

This doesn't log to the console. I suspect that the reference to `aws-sdk/S3` might be invalid, or that at this point it is too late to intercept the library?

**Comment by theKashey** [comment]
That will not work as long you already `import` fetchObjectFromS3, and any changes made after it will not affect already created variables. That's a laws of javascript.

There is 2 ways to solve it:
- remove import from the top, and require/import file after rewiremock.enable(). Or you can use any other API provided by rewiremock. But you have to import `fetchObjectFromS3` after you configure rewiremock.
- if you are able to use babel, you may "hoist" rewiremock before imports, and it will work as jest.mock - magically. Not sure that babel is an option for you. 

So, the best approach:
```js

  it.only('should fetch an object from s3 with from object info', async () => {
   if(0) { // dont do *this*, you are not removing mock, and soiling other tests
    rewiremock('aws-sdk/S3').with({
      getObject: (): void => {
        console.log('get object was called')
      }
    })
   }
 
// "proxy" - the simplest, but not "type safe" API
   const fetchObjectFromS3 = rewiremock.proxy('../src',{
    'aws-sdk/S3': {
      getObject: (): void => {
        console.log('get object was called')
      }
    }
  } 

// "module" - "Typed" API, probably use this.
   const fetchObjectFromS3 = await rewiremock.module(() => import('../src'), {
    'aws-sdk/S3': {
      getObject: (): void => {
        console.log('get object was called')
      }
    }
  } 


    const file = await fetchObjectFromS3({
      bucketArn: 'arn:aws:s3:::myarn',
      objectKey: 'alpha/a-company/input/test.txt'
    })

    console.log(file)
  })
```
