### ISSUE TITLE
Jest: Setup problems

### ISSUE THREAD

**Issue by Darmikon** [theKashey/rewiremock#4]
Hi, could you please tell me if I'm doing something wrong with setup.
I tried to follow your specs but I don't see any results at the moment.
What I'm trying to do is to mock external dependency `intl-locales-supported` so that it returns
custom result instead of real one. But `rewiremock('intl-locales-supported')...` and `rewiremock.enable();` do nothing. It doesn't work if I even try to mock main file itself `rewiremock('../core')...` . Maybe I missed something important in configuration. I'm running tests using `jest`.
Thanks in advance.

```
// i18n.spec.js
...
import rewiremock from 'rewiremock';
...
beforeAll(() => {
  rewiremock('intl-locales-supported')
	.with(() => {
	  return '------test-------';
	});

  rewiremock.enable();
  const mockedCore = require('../core');
  mockedCore.localeLoaders.en();
});
afterAll(() => {
  rewiremock.disable();
});
.	
...

// core.js
...
import isIntlLocaleSupported from 'intl-locales-supported';

export const localeLoaders = {
  en: async () => {
    // TODO remove
    console.info(isIntlLocaleSupported('en'));
    if (global.Intl && isIntlLocaleSupported('en')) {
...


// .babelrc
...
"test": {
      "plugins": [
        "transform-promise-to-bluebird",
        "transform-decorators-legacy",
        "dynamic-import-node"
      ]
    }
...
```

**Comment by theKashey** [comment]
Jest :) 👽 
I should indicate some issues with Jest in the readme, but not I did it better
-- version 3.10 ships with improved Jest support --
All you have to do - disable automocking (look like it is disabled), execute one like of code, and use another.
```js
// import rewiremock
import rewiremock from 'rewiremock';

// "fix" rewiremock
rewiremock.overrideEntryPoint(module); // jest :(

// get "unhacked" require
const rightRequire = rewiremock.requireActual;
// or
require = rewiremock.requireActual;

next - require files using it
```

Problem is simply - Jest do have it's own mocking and sandboxing system. You cannot bypass or alter it.
Jest system is quite strange, as long they pass throughout all node_modules but transform and sandbox all client code...

Anyway - try this out. 

PS: you might have correct babel setup to be able run tests without jest transforms.

**Comment by Darmikon** [comment]
@theKashey Thanks for the feedback. Unfortunately I couldn't run your mock. Here is the code:
```
// package.json
"rewiremock": "^3.1.0",
```

```
// __tests__/core.spec.js
...
import rewiremock from 'rewiremock';

rewiremock.overrideEntryPoint(module); // jest :(
      const rewire = rewiremock.requireActual;
      rewire('../core')
        .with(() => {
          return '------test-------';
        });
      rewire.enable();
      console.info(require('../core'));
```
And here is an error in console
```
 \src\__i18n__\core.js:1
    (function (exports, require, module, __filename, __dirname) { import { addLocaleData } from 'react-intl';
                                                                  ^^^^^^
    SyntaxError: Unexpected token import
      
      at createScript (vm.js:53:10)
      at Object.runInThisContext (vm.js:95:10)
      at Module._compile (module.js:543:28)
      at Object.Module._extensions..js (module.js:580:10)
      at Module.load (module.js:488:32)
      at tryModuleLoad (module.js:447:12)
      at Function.Module._load (module.js:439:3)
      at requireModule (node_modules/rewiremock/lib/executor.js:50:47)
      at Object.require (node_modules/rewiremock/lib/module.js:57:40)
      at Object.<anonymous>.mockModule.requireActual (node_modules/rewiremock/lib/mockModule.js:243:29)

```
core.js uses es6 imports

```
// core.js
import { addLocaleData } from 'react-intl';
import isIntlLocaleSupported from 'intl-locales-supported';

...
```

**Comment by theKashey** [comment]
Yep, cos rewiremock.requireActual bypasses Jest infrastructure, thus ignores code transformation. The only way is to run Jest under Babel management.
Just mention babel inside `describe` or `it` block. The point is - you __can not__ do it on the top level - Jest sandboxing will wipe away this sort of settings on test spawn. 
```js
require("babel-register");
```
This will activate babel, __not affecting__ Jest, as long it does not use nodejs's require-extension mechanics (that's bad).

PS: Jest will force BABEL_ENV to be `test`, please ensure that you have it configured.

**Comment by theKashey** [comment]
But you will loose `jest` variable inside re-mocked file :(
