### ISSUE TITLE
TS2536: Type '"default"' cannot be used to index type 'Ts'. After upgrading to TS 3.1.1

### ISSUE THREAD

**Issue by mpsijm** [theKashey/rewiremock#43]
I just tried upgrading my TypeScript app from TS 3.0.1 to 3.1.1. When compiling it with `webpack`, having `rewiremock` as one of our (dev-)dependencies, compilation breaks at this point:

```
    ERROR in [at-loader] ./node_modules/rewiremock/rewiremock.d.ts:122:66 
        TS2536: Type '"default"' cannot be used to index type 'Ts'.
```

Interestingly, when I compile with `tsc`, I do not get this error.

**Comment by theKashey** [comment]
Did not tried TS 3 yet.

**Comment by theKashey** [comment]
I've simplified dts, and trying to understand why it was so complex.
Should work fine with 3.8.0

**Comment by mpsijm** [comment]
Yes, works for me! Thanks a lot :slightly_smiling_face:
