### ISSUE TITLE
Not working in Babel v8

### ISSUE THREAD

**Issue by chuckcarpenter** [theKashey/rewiremock#45]
After updating to Babel 7 the web pack build no longer works. 

```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/chuckcarpenter/Projects/lift-anonymous/node_modules/rewiremock/babel.js
    at createDescriptor (/Users/chuckcarpenter/Projects/lift-anonymous/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/chuckcarpenter/Projects/lift-anonymous/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
```

**Comment by theKashey** [comment]
You mean - babel 7?

**Comment by chuckcarpenter** [comment]
Yes! Sorry, was looking at another package version. After update gives that error. Can’t seem to tell why, any ideas?

**Comment by theKashey** [comment]
I'll test. No ideas yet, but should be something oblivious.

**Comment by msaglietto** [comment]
Hey .. thanks theKashey 

I tried the 3.11 version with babel-register 7 and its working :+1: 

but for some reason I had to add the file that is importing the mock to rewiremocks  .. like 
```
    rewiremock("@something/module").es6().withDefault(() => () => stub).toBeUsed();
    rewiremock("the.controller.that.import.module").es6();
    rewiremock.enable();

    // Use require to work with rewiremock
    server = require("./server.mock").default;
```

**Comment by theKashey** [comment]
@chuckcarpenter - sorry, forgot to mention - rewiremock babel plugin now works fine with babel 7.

@msaglietto - are you using babel plugin, or just babel-register (if yes - that would be another issue)

**Comment by msaglietto** [comment]
Im using babel-register with the babel plugin on babelrc
