### ISSUE TITLE
It is not possible to mock non-existing files(?)

### ISSUE THREAD

**Issue by kennethlynne** [theKashey/rewiremock#46]
I can not figure out why

```js
rewiremock('../something').with({});
console.log(require('../something')); // module '../something' does not exit
```
does not work but
```js
rewiremock('../existing').with({});
console.log(require('../existing')); // {}
```
does.

Is it possible to mock files that do not yet exist like for example mock-require does?

```js
mockRequire('../something', {});
console.log(require('../something')); // {}
```

**Comment by theKashey** [comment]
It's possible, but I am actually planning to disable this possibility at all, to make life easier - not let you to make a mistake.

Is there any reason to import something non existing in your case?

**Comment by kennethlynne** [comment]
I am unit testing a script that should require and execute some files based on a parameter.

Basically, tell a script that we want to do X, and the handler will require X.js and it will do something with that file, like call some methods etc.

So if you disable it by default I urge you to make it possible and easy to circumvent it.

But you say it is currently possible? I was not able to get it to work and I did not find the answer in the documentation, could you please provide an example?

**Comment by theKashey** [comment]
Rewiremock could mock everything, but it's a tricky thing to explain what to mock. Stuff like _relative names_ may cause some issues.
Let me double check it.

**Comment by theKashey** [comment]
So - it was not possible before :)
