### ISSUE TITLE
the npm module lib folder is missing the toMatchOrigin file

### ISSUE THREAD

**Issue by nathanvale** [theKashey/rewiremock#5]
var _toMatchOrigin = require('./toMatchOrigin');

​​Error: Cannot find module './toMatchOrigin' from 'index.js'​​

**Comment by theKashey** [comment]
@nathanvale looking.. Where is message is from ? plugins/index.js?

**Comment by theKashey** [comment]
Never ever use async stuff in build.

Next thing to build: npm module post-build verification

**Comment by theKashey** [comment]
Patch version released.
