### ISSUE TITLE
Unable to mock function using proxy

### ISSUE THREAD

**Issue by ptrupti** [theKashey/rewiremock#53]
Hi,

I am very new to this so I may be running into this issue.
I have an entry module app.js which imports a different module which I need to mock for my tests.
So app.js is a class extending react component.
and the module I want to stub exports a default function.
I am not able to get this working and keep hitting an error: Cannot read property 'call' of undefined.

Below is my code:
```js
describe('HTMLUITests', () => {
  it('Init should initialize correctly', () => {
    var urlParams = {port: '13871', storeId: '51105455', locale: 'en', os: 'Windows'};
    var getUrlVars = function(location) { return urlParams; }

     const f = rewiremock.proxy('../src/app', {
       './UrlParameters' : getUrlVars
     });
   });
});
```
The error I get is 
```
 TypeError: Cannot read property 'call' of undefined
        at __webpack_require__ (test-bundles/runtime.js:783:30)
        at Array.fn (test-bundles/runtime.js:151:20)
        at baseLoader (test-bundles/commons.js:116023:39)
        at Object.mockLoader [as _load] (test-bundles/commons.js:113697:72)
        at RQ (test-bundles/commons.js:116031:16)
        at requireModule (test-bundles/commons.js:113463:12)
        at Object.require (test-bundles/commons.js:114704:75)
        at Function.push../node_modules/rewiremock/es/mockModule.js.mockModule.requireActual (test-bundles/commons.js:114461:58)
        at test-bundles/commons.js:114317:27
        at Function.push../node_modules/rewiremock/es/mockModule.js.mockModule.inScope (test-bundles/commons.js:114353:5)
        at Function.push../node_modules/rewiremock/es/mockModule.js.mockModule.proxy (test-bundles/commons.js:114310:14)
        at Context.<anonymous> (test-bundles/htmlui-test.js:66:34)
```
Any help is appreciated ! 
Thanks
Trupti.

**Comment by ptrupti** [comment]
Actually I dont have above error any more after I modified my code:

import { expect } from 'chai';
import  getUrlVars  from '../src/UrlParameters';
import App from '../src/app';
import  sinon  from 'sinon';
import rewiremock from 'rewiremock';

describe('HTMLUITests', () => {
  it('Init should initialize correctly', () => {
    var urlParams = {port: '13871', storeId: '51105455', locale: 'en', os: 'Windows'};
    const mock = rewiremock.proxy('../src/app', {
      './UrlParameters' : new function(args) {
         return urlParams;
      }
    });
     console.log(mock);
    });
  });

But the mock is always undefined.

**Comment by ptrupti** [comment]
Thanks for the quick response!How do you enable the plugin?I only added it through yarn add .
Thanks Trupti 


Sent from Yahoo Mail for iPhone


On Wednesday, October 24, 2018, 8:27 PM, Anton Korzunov <notifications@github.com> wrote:


Have you enabled rewiremock webpack plugin?
Error sounds like the file, you are trying to import, does not exists. But then second code also should not work.
If you are able to give me some example, I just could run and debug, then I would able to find the roots of this issue quite quickly.

**Comment by theKashey** [comment]
See readme - https://github.com/theKashey/rewiremock#to-run-inside-webpack-enviroment
You have to add something like 3 plugins for webpack to make it live.

**Comment by ptrupti** [comment]
Sorry to bother you again but we don’t use webpack we only use node.js

**Comment by ptrupti** [comment]
Thanks. After some more digging I figured out that we already have these plugins. 
The second code is my main issue currently.
Latest test code:

import { expect } from 'chai';
import App from '../src/app';
import  sinon  from 'sinon';
import rewiremock from 'rewiremock';


describe('HTMLUITests', () => {
  it('Init should initialize correctly', () => {

    var urlParams = {port: '13871', storeId: '51105455', locale: 'en', os: 'Windows'};
    const app = rewiremock.proxy('../src/app', {
      './UrlParameters' : new function(location){
        return urlParams;
      }
    });
    console.log(App);
    console.log(app);
    });
  });

Here the console.log(App) which is the import without mock is logged as : function App(props) { ... }
but the second line (the mocked object) is logged as Object{default: function App(props) { ... }} How do I get the App from the mocked object?

**Comment by theKashey** [comment]
so `rewiremock.proxy` is basically a __require__, so - 
```js
const app = rewiremock.proxy('../src/app', {
  './UrlParameters' : new function(location){
    return urlParams;
  }
}).default; // as usually you have to do with "es5" modules in nodejs
```

**Comment by theKashey** [comment]
If you are using babel give a shot to a ["hoisted" mocks](https://github.com/theKashey/rewiremock#hoisted-mocking)
https://github.com/theKashey/rewiremock/tree/master/_tests/babel/test
https://github.com/theKashey/rewiremock/blob/master/_tests/babel/test/dynamic.spec.js

**Comment by ptrupti** [comment]
Thanks! That did it!


Sent from Yahoo Mail for iPhone


On Thursday, October 25, 2018, 3:35 PM, Anton Korzunov <notifications@github.com> wrote:


so rewiremock.proxy is basically a require, so -
const app = rewiremock.proxy('../src/app', {
  './UrlParameters' : new function(location){
    return urlParams;
  }
}).default; // as usually you have to do with "es5" modules in nodejs

**Comment by theKashey** [comment]
Good luck then
