### ISSUE TITLE
Unable to import rewiremock into .jsx file

### ISSUE THREAD

**Issue by Digadadave** [theKashey/rewiremock#56]
Thanks for this tool, it has been wonderful for node tests.

I'm using webpack 4 with Karma, and I am having an issue when using rewiremock while testing `.jsx` files.  Would this be an issue with rewiremock, or something in my karma config?  I have not had issues with any other imports.

```
import rewiremock from 'rewiremock/webpack';

// Error:
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR   
  SyntaxError: Unexpected token 'const'
```

When not using the webpack module (`mport rewiremock from 'rewiremock';`) I get this:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Expected an identifier but found '{' instead
```

What other information would you need from me?

Thanks,
-Dave

**Comment by Digadadave** [comment]
Never mind.  After spending a few hours on this, and creating this issue, it occurred to me that PhantomJS is on the out and I should try switching to ChromeHeadless.  Switching to ChromeHeadless fixed this and I'm back to using this fantastic tool.

Thanks again

**Comment by theKashey** [comment]
It sounds like `babel` problem. Switching to Chrome just let you digest that `const`, Phantom couldn't.
