### ISSUE TITLE
Supporting non-modern (ES5) browsers

### ISSUE THREAD

**Issue by ljqx** [theKashey/rewiremock#57]
Though `rewiremock` itself is built into ES5 & ES6, the `rewiremock/webpack/interceptor` is still ES6 only. Which limits it's usage in non-modern browsers like IE11.

Better to make `rewiremock/webpack/interceptor` ES5 compatible to ease the adoption. It would be an easy change. If it's ok I can make the change and add lint for it to prevent future break.

**Comment by theKashey** [comment]
Sounds easy to do - just replace cost `let`/`const` by a var.
I would be happy if you will do it.

**Comment by theKashey** [comment]
Released in __beta__ channel as 3.12.0.
@ljqx , @suro1995 - please ensure that everything is now working as it should.

**Comment by suro1995** [comment]
Still found several issues:
Tow of them are addressed in PR: https://github.com/theKashey/rewiremock/pull/61/files
One needs further discussion: 
* How do we deal with `array.prototype.find` which is widely used in the source code?

Possible solutions:
1. [babel-plugin-transform-array-find](https://www.npmjs.com/package/babel-plugin-transform-array-find) - Does not seem very popular.
2. Use babel-polyfill - but production environment may not have polyfill, so does not make much sense to ployfill in test environment. 
3. Change the source code to be compatible - Use lodash find or something.

**Comment by theKashey** [comment]
I went with .2 way. Always polyfill for IE. Don't it make another-browser-experience worse.
Especially in the tests.

**Comment by suro1995** [comment]
The only concern about 2 is whether to assume all production environments have the polyfill.  
For the ones do not have polyfill, they may not want to polyfill in tests neither.

**Comment by theKashey** [comment]
If there is only one place with `.find`, then probably it worth to use `lodash`. But I am not sure someone will not have a polyfill for so usable thing.

**Comment by theKashey** [comment]
@suro1995 - v3.12.2 with all your stuff inside just shipped.

**Comment by suro1995** [comment]
Oh, there is one more PR - https://github.com/theKashey/rewiremock/pull/62
That finally made everything needed for IE11

Could you also help take a look, thanks!

**Comment by theKashey** [comment]
:animated_fireworks.gif:
