### ISSUE TITLE
Using webpack context configuration property stops mocking from working

### ISSUE THREAD

**Issue by bameyrick** [theKashey/rewiremock#66]
I may be configuring something incorrectly, but I've found when using the [context](https://webpack.js.org/configuration/entry-context/#context) configuration property in a webpack config, mocking fails.

I created a simpler repository to check this here: https://github.com/bameyrick/rewiremock-test

In the master branch I have a version where I'm not using the `context` property in the webpack config. If I run `yarn test` the mocking works correctly.

However in the [using-context branch](https://github.com/bameyrick/rewiremock-test/tree/using-context) where I've added a `context` property in the webpack config, a `basePath` in the karma config and updated the path to  mock [fetch.js](https://github.com/bameyrick/rewiremock-test/blob/using-context/src/js/fetch.js) in [index.spec.js](https://github.com/bameyrick/rewiremock-test/blob/using-context/src/tests/index.spec.js), it seems that rewiremock finds `fetch.js` for mocking but does not replace it with [fetch.stub.spec.js](https://github.com/bameyrick/rewiremock-test/blob/using-context/src/tests/fetch.stub.spec.js).

I tried `console.log(__webpack_modules__)` in the `using-context` branch and could see `./js/fetch.js` in there, and rewiremock doesn't complain that it can't find it, but it doesn't seem to mock the fetch function.

**Comment by theKashey** [comment]
100% that rewiremock does not handle this feature at all. I'll try to investigate the problem.
Meanwhile - there is another, absolutely unbreakable (and typeable!) way to mock:
```js
rewireMock(() => require('./src/js/fetch')) // webpack will handle this `require`
  .withDefault(mockedFetch);
```
