### ISSUE TITLE
Support custom webpack config filenames on webpackAlias plugin.

### ISSUE THREAD

**Issue by alexkrautmann** [theKashey/rewiremock#7]
I am trying to use my webpack aliases with rewiremock as described in [README.md](https://github.com/theKashey/rewiremock/blob/master/README.md#plugins)

However, I get the following error:

```
  1) LazyImg
       binds classes with styles:
     Error: Cannot find any of these configuration files: webpack.config.js, webpack.config.babel.js
      at readAliases (node_modules/rewiremock/es/plugins/common/aliases.js:55:1)
      at configure (node_modules/rewiremock/es/plugins/webpack-alias.js:7:1)
      at Object.fileNameTransformer (node_modules/rewiremock/es/plugins/webpack-alias.js:12:1)
      at node_modules/rewiremock/es/plugins.js:21:1
      at Array.reduce (<anonymous>)
      at convertName (node_modules/rewiremock/es/plugins.js:19:1)
      at mockModule (node_modules/rewiremock/es/mockModule.js:37:1)
      at node_modules/rewiremock/es/mockModule.js:145:1
      at Array.forEach (<anonymous>)
      at node_modules/rewiremock/es/mockModule.js:144:1
      at Function.__dirname../node_modules/rewiremock/es/mockModule.js.mockModule.inScope (node_modules/rewiremock/es/mockModule.js:186:1)
      at Function.__dirname../node_modules/rewiremock/es/mockModule.js.mockModule.proxy (node_modules/rewiremock/es/mockModule.js:143:1)
      at Context.<anonymous> (src/webapp/app/components/LazyImg/LazyImg.spec.jsx:13:36)
```

It looks like rewiremock plugins need to accept configuration so we can point webpackAlias plugin to the correct webpack config instead of depending on the default config options 'webpack.config.js' and 'webpack.config.babel.js' seen [here](https://github.com/theKashey/rewiremock/blob/master/src/plugins/common/aliases.js#L7). 

I am willing to help out, but wanted to run this by you before attempting to make a PR in case you have any ideas on how to support this.

**Comment by theKashey** [comment]
There is a command to setup webpack configuration, but it is not quite pretty :) 
```js
import {configure} from 'rewiremock/lib/plugins/webpack-alias';

configure('YOUR_WEBPACK_FILE');
```

**Comment by theKashey** [comment]
Any luck?

**Comment by Alex-Krautmann** [comment]
I actually ran into some other issues getting rewiremock to work at all with mocha-webpack. I haven't looked at this in a few days, but am getting back into it today. I will update if I get more info.

**Comment by theKashey** [comment]
Dont forget to fill an issue.

**Comment by pribilinskiy** [comment]
@theKashey I am trying to merry rewiremock with storybook. So far so bad )
Documentation is not clear and there's no example on how to use in an environment like storybook config.

In our case the webpack config file is called `webpack.dev.js` and it's in the root of the repo and it has aliases. I'm trying to replace imported libraries in `.vue` files by those in `__mocks__` folder.

The storybook config is located in `.storybook/config.js` file
I put  following into `config.js`:

```
import { addPlugin as addRewiremockPlugin, plugins } from 'rewiremock';
import { configure as configureRewiremockAliases } from 'rewiremock/lib/plugins/webpack-alias';

addRewiremockPlugin(plugins.webpackAlias);
configureRewiremockAliases('webpack.dev.js');
```

and getting an error:

```
aliases.js:68 Uncaught Error: Cannot find any of these configuration files: webpack.dev.js, webpack.config.js, webpack.config.babel.js
```

Changing the path to `../webpack.dev.js` results in a slightly different error )

```
aliases.js:68 Uncaught Error: Cannot find any of these configuration files: ../webpack.dev.js, webpack.config.js, webpack.config.babel.js
```

I looked into `aliases.js` and there's this line:
```
    var resolvedConfigPath = (0, _path.resolve)(process.cwd(), compiledConfigPath);
```

and it's logical, calling `process.cwd()` in the browser results in `/` , no wonder why path is not resolved

In `.storybook/webpack.config.js` I've added following lines as described in documentation:

```
const RewiremockPlugin = require("rewiremock/webpack/plugin");
module.exports = (storybookBaseConfig, env, storybookConfig) => {
  storybookConfig.plugins.push(
    new RewiremockPlugin(),
  );
  return storybookConfig;
};
```

and following is added to `.babelrc`

```
"plugins": [
  "rewiremock/babel", // babel plugin is required to use "Jest-style" mocking
]
```

as described in [this Medium article](https://medium.com/@antonkorzunov/rewrite-a-storybook-ae4682176cc3)

nevertheless even without aliases following doesn't work:
```
rewiremock('../components/dep').by('../components/__mocks__/dep');
```

Am I correct if the issue with aliases is resolved it will be enough to write similarly to `jest.mock`:
```
rewiremock('components/dep');
```

Though following works
rewiremock('../components/dep').by(() => 'test');

Contents of `dep.js`:

```
export default function () {
  return 'test';
}
```

**Comment by theKashey** [comment]
🥇 👍 
You did some things I never did in the past. And all are valid, and all I have to fix.
There is one "real mistake" - `.vue` in not in the extension list, and would be __never__ autoresolved. 
```js
import {resolveExtensions} from 'rewiremock';
resolveExtensions(['.vue', '.js', '.what-else-you-need']);
```
That would be a first step, and it may solve something.

Second - while I expect `webpack.conf` to return json - just help me
```js
addPlugin(plugins.webpackAlias);
configure('webpack.rewiremock.js');

// webpack.rewiremock.js
modules.export = require('./webpack.dev.js')(); // would it work?
```
And then - require this file, thus put it into "modules list", and let rewiremock read it.

**Comment by pribilinskiy** [comment]
Thanks for your help!

I had the idea of creating a webpack config that calls our config

Unfortunately that didn't helped too (

![image](https://user-images.githubusercontent.com/3078595/50862865-77166a00-13a5-11e9-8d3b-a3fabf8ff0d4.png)

Added `resolveExtensions` to `.storybook/webpack.config.js` to no avail
![image](https://user-images.githubusercontent.com/3078595/50863062-24897d80-13a6-11e9-908c-52b5d475ee30.png)

`by` can't  find the module even when explicitly providing the path
```
rewiremock('../components/dep').by('../components/__mocks__/dep');
```

looks like the library is broken in some places

**Comment by pribilinskiy** [comment]
I see, makes sense. [The docs are too concise](https://github.com/theKashey/rewiremock#automocking)
"_Just create \_\_mocks\_\_/fileName.js_" is definitely not enough :)

Still, support for webpack aliases is a must, especially the `@ => src/` alias

**Comment by theKashey** [comment]
Documentation was created for nodejs 🤗. Thank you for this issue, now I know what I should fix for webpack.

**Comment by theKashey** [comment]
If your test runner is working with aliases in the code, then `node` could resolve corrent names by itself. For example I use [require-control](https://github.com/theKashey/require-control#4-to-control-path-resolution) for it.

In this case using `node` plugin instead of `webpack-alias` would work out of the box, with one moment - it will resolve file names from the "test" file, not from the "tested".

However, you can write plugin which does what you need by yourself:
```js
// adds `..` for every stub to support `stuff.js <- _tests/stuff.test.js`
const getParentDirectory = (file: string) => {
  // if referenced relative to the "current" file - the file is one folder above
  if (file.startsWith('../')) {
    return `../${file}`;
  }
  if (file.startsWith('./')) {
    return `.${file}`;
  }
  return file;
};

addPlugin({
  fileNameTransformer: (fileName: string, module: any) => {
    return (Module as any)._resolveFilename(getParentDirectory(fileName), module);
  },
});
```
