### ISSUE TITLE
How to simply mock a child react component?

### ISSUE THREAD

**Issue by kxiang2016** [theKashey/rewiremock#73]
Say I want to unit test component "Account".  It is
```js
class Account extends Component {
 render() {
   return(
  <Type>
     ....
   </Type>
);
}
```
 And in my test, I want to mount Account like
```js
const wrapper = mount(
         <MemoryRouter initialEntries={[ '/xxxxx' ]}>
            <Account/>
         </MemoryRouter>
)
```
I have a  mocked the Type component.  How to replace the real Type with my MockType? Tried several ways, not working. I am pretty new.  Thanks for any help

**Comment by theKashey** [comment]
It depends on _where_ is Type. 
- If type is another module, relatively to `Account` - you can use `rewiremock` to replace __import__ of it, and thus mock
- in other cases - use [react-remock](https://github.com/theKashey/react-remock) to mock any type anywhere
```js
import {remock} from 'react-remock';

remock(Type); // done, it's gone.
```

**Comment by kxiang2016** [comment]
Appreciate your quick response.  Yes, "Type" just another React component, which "Account" depends on.  I want to mock it.  Is rewiremock can mock it with my simple component like <div>Mock</div>? right now we cannot use react-remock

**Comment by kxiang2016** [comment]
Appreciate your quick response.  Yes, "Type" is another react module.  I am pretty new, could you point how to replace the import ? I tried 
const Account = rewiremock.proxy('../src/account', {
         './type/dist/index.js': { Type: MockType },
       });

and
 
rewiremock('./Type/dist/index.js').by('./mock-type.js');

No one works.   Can you give a example ? Thank you.

**Comment by theKashey** [comment]
What’s your testing framework? If you are using jest - you have to use jest.mock

**Comment by kxiang2016** [comment]
We are not using jest right now.  We used rewiremock before. But we only used it for mock a function using rewiremock.proxy.  So rewiremock cannot mock a whole react component? Or there are just some error in my test code?

**Comment by theKashey** [comment]
There should be an error, and quite obvious. Try enable some checks
```js
import rewiremock, { addPlugin, plugins } from 'rewiremock';

addPlugin(plugins.relative); // help ensure file you wanna mock exists
addPlugin(plugins.usedByDefault); // ensures that you mock the file you gonna use

// ....

// do mock
```
It will point you on the error.

**Comment by kxiang2016** [comment]
Thanks. And Is my syntax correct?
const Account = rewiremock.proxy('../src/account', {
'./type/dist/index.js': { TypeComponent: MockTypeComponent },
});
const wrapper = mount(
         <MemoryRouter initialEntries={[ '/xxxxx' ]}>
            <Account/>
         </MemoryRouter>
)

I tried addPlugin.  And get Error: 
./type/dist/index.js is set toBeUsed, was requied, by rejected by plugins. What does this mean?

**Comment by theKashey** [comment]
- Yes. The usage is correct.
- Probably you need `rewiremock.proxy(...).default` if `Account` is a __default export__.
- that means that `./type/dist/index.js` was not mocked. Ie on some stage something said `shouldMock? - NO!`. And that message should include the plugin name.
