### ISSUE TITLE
callThrough in rewiremock/node

### ISSUE THREAD

**Issue by atorma** [theKashey/rewiremock#74]
I'm trying to replace one method of a dependency using rewiremock/node (version 3.13.0)  and `callThrough().with(stubs)`. However, the module under test gets the mocked dependency replaced entirely by `stubs`. Calling a non-stubbed method of the dependency fails because the method isn't available.

The code is something like this:

A dependency 
```javascript
module.exports = {
  doOneThing() {
  },
  doAnotherThing() {
  }
};
```

Module under test
```javascript
const dependency = require('./dependency');

module.exports = {
  methodUnderTest() {
    dependency.doOneThing();
    dependency.doAnotherThing();
  }
};
```

Mocha test
```javascript
const rewiremock = require('rewiremock/node');
let serviceUnderTest;
let stubs;

beforeEach(function() {
  stubs = {
    doOneThing: sinon.stub()
  }; 
  serviceUnderTest= rewiremock.proxy(
    './service-under-test',
      r => ({
        './dependency': r.callThrough().with(stubs)
      })
  );
  
  // Does not work either!
  // rewiremock.enable();
  // rewiremock('./dependency')
  //  .callThrough()
  //  .with(stubs);
  // serviceUnderTest = require('./service-under-test');
  // rewiremock.disable();  
});

it('should call dependency.doAnotherThing', function () {
   serviceUnderTest.methodUnderTest(); // fails because dependency.doOneThing is not a function (but undefined)
});
```

Am I doing something wrong? Or is there someting wrong with how `.callThrough()` works with NodeJS (version 10) `require`?

**Comment by theKashey** [comment]
Everything is absolutely right. Let me add your example into the test suite and debug.

**Comment by theKashey** [comment]
I've added a test for your case, and it's green. Something else is broken.

**Comment by atorma** [comment]
I think I narrowed down the problem: `.callThrough()` does not work if the original module exports a class instance and the method to call through to is a prototype method. It works OK if the original module exports a plain object instance and the method to call through to belongs to the instance.

I created a minimal test case here: https://github.com/atorma/rewiremock-test.

There is also a mistake in my earlier example. It should have 
```javascript
stubs = {
  doAnotherThing: sinon.stub()
}; 
``` 
so that the method to call through to is `doOneThing` which is called first by the service under test. Sorry about that.

**Comment by theKashey** [comment]
That's interesting! Looking into it.

**Comment by theKashey** [comment]
Because prototype is rejected during `callThrought` and proper support for it makes everything easier!

**Comment by theKashey** [comment]
Just update to a new, v3.13.3, version.

**Comment by atorma** [comment]
Works for me, thanks!
