### ISSUE TITLE
Overriding same module dependencies

### ISSUE THREAD

**Issue by dcusan** [theKashey/rewiremock#8]
This looks interesting but I'm rather new to dependency injection in JS and I have a question.

I was wondering if there was a way for me to override a function from within the same module? I am doing something similar to this:

```javascript
// module.js
export default {
  doA,
  doB
};

export function doA() {
  const b = doB();
  return "a" + b;
}

export function doB() {
  return "b";
}
```

```javascript
// test.js
import rewiremock from "rewiremock";
import { expect } from "chai";

describe("moduleTest", function() {
  it("adds a", function() {
    // mock setup
    rewiremock("./module")
      .callThrough()
      .with({
        doB: () => "a"
      });

    rewiremock.enable();

    const mockedModule = require("./module");
    expect(mockedModule.doA()).to.equal("aa");

    rewiremock.disable();
  });
});
```

This test will fail for me returning `"ab"` in node 8.9.3. What am I doing wrong?

Any comment is appreciated, thank you!

**Comment by theKashey** [comment]
No, it will not work. Let me explain why.
1. doA calling doB as local variable. There is no way to override local variable.
2. it is possible to address doB from the exports
```js
 const myExports = { doA, doB }
 export default myExports;
 export function doA() {
  const b = myExports.doB();
  return "a" + b;
}
```
and next
```
import test from './test.js';
test.doB = () => "a";
test.doA() === 'aa'; 
```
This is a common approach in commonJS, and someone it even calling it "Mocking". 
Have a look on this -> https://codeburst.io/stub-dependencies-with-sinon-js-259ac12379b9
But it will not gonna work properly with ES6 imports/exports. Just awkward.

3. As long this is not dependency "mocking", but a single module "hacking" - rewiremock cant do anything. It works only with real dependencies. 

You have to extract function to external files, make code mode composable or introduce IoC to reach the goal.

**Comment by dcusan** [comment]
Thank you for your answer, very much appreciated!

I'll look into maybe splitting up the module.
