### ISSUE TITLE
Storybook built version stories crashing when using rewiremock

### ISSUE THREAD

**Issue by Knskan3** [theKashey/rewiremock#89]
**Describe the bug**
When building storybook statically, the stories using `rewiremock` crash.

**To Reproduce**
1. Create a story
2. Install and import `rewiremock`
3. Create a mock like
```
rewiremock('./helpers/sessionHistory')
  .callThrough()
  .with({
    getLastSession: () => ({
      email: 'mocked-mail',
      name: 'mockedName',
    }),
  })
  .toBeUsed(); // always check was the mock used, or not.

```
4. Build storybook
5. Open the static page.

<img width="706" alt="Screenshot 2019-07-03 at 13 41 52" src="https://user-images.githubusercontent.com/1422357/60589021-b512aa80-9d98-11e9-83c2-6645805088d3.png">

**Comment by theKashey** [comment]
#### Could be due:
- `hot` is not enabled.
- `HotModuleReplacementPlugin` present twice.

#### How to test:
`console.log(module.parents)` should be not null.

#### How to fix:
Check your storybook webpack config.

**Comment by Knskan3** [comment]
Hi, 
I added the  `HMR` plugin and the error persisted, but then I forced `development` mode to the webpack config  (the build was using prod by default) and it worked. 

Thanks
