### ISSUE TITLE
"Cannot read property 'parentScope' of null" when clearing require.cache without executing rewiremock.disable()

### ISSUE THREAD

**Issue by PatrickShaw** [theKashey/rewiremock#90]
If you clear the require cache without running `rewiremock.disable()`, you run into the following error: 
```
TypeError: Cannot read property 'parentScope' of null
    at collect (node_modules\rewiremock\lib\mocks.js:87:15)
    at collectMocks (node_modules\rewiremock\lib\mocks.js:95:3)
    at getAllMocks (node_modules\rewiremock\lib\mocks.js:100:10)
    at wipeCache (node_modules\rewiremock\lib\wipeCache.js:33:31)
    at Function.mockModule.flush (node_modules\rewiremock\lib\mockModule.js:312:29)
    at Function.mockModule.clear (node_modules\rewiremock\lib\mockModule.js:348:16)
    at Object.<anonymous> (node_modules\rewiremock\lib\index.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
```

Not sure why or whether it can be avoided but I ran into the error today.

Here's a pretty small example that replicates the issue:
`index.js`
```js
for(let i = 0; i < 200; i++) {
  const rewiremock = require('rewiremock').default;
  rewiremock('./index2').with({ printSomething: () => console.log('something different')});
  rewiremock.enable();
  const { printSomething } = require('./file2');  
  printSomething();

  for(const key of Object.keys(require.cache)) {
    delete require.cache[key];
  }
}
```

`file2.js`
```js
module.exports.printSomething = () => {
  console.log('yay');
};
```

**Comment by PatrickShaw** [comment]
Note that I'm aware you can avoid `enable()` and `disable()` by using `around(...)`

**Comment by theKashey** [comment]
First of all -  Don't touch the cache! Shame on you!

Look like the problem is not with deinitialization, but with initialization - the `scope` is undefined.
The only way to cause it - don't clear cache properly, or somehow poison it with other stuff.

`rewiremock/lib/mockModule.js:56: updateScope` is not called the second time, so `scope` is null

**Comment by theKashey** [comment]
`around` or `inScope` also would help you to isolate mocks from each other.

Anyway - I'll double check.

**Comment by PatrickShaw** [comment]
Thanks for looking into it

Also, had to touch the cache :3 
I'm writing a testing framework as part of my honours project - Gotta reset the modules after a test suite runs (if there's a better way let me know though :) ).

**Comment by theKashey** [comment]
1. There is a bug with cache clearance - right now it's clearing __less__ that it could. Gonna release a fix as a major version bump.
2. Wiping modules is a good practice to create alternate realities, although not the safest. Look for vm.context and other sandboxes (Jest uses it) - https://nodejs.org/api/vm.html

**Comment by PatrickShaw** [comment]
Great :) 

Ooo, I'll look into it, thanks for letting me know, helpful as always.

**Comment by svmn** [comment]
How should I make a clean state between tests?
I have a lot of files where some initialization is made during require, so in order to reload things I need to wipe the cache.

**Comment by theKashey** [comment]
You're welcome :)
