### ISSUE TITLE
webpack-mocha workaround does not work in newer versions

### ISSUE THREAD

**Issue by dcadez** [theKashey/rewiremock#95]
Hi,

I'm trying to set up rewire-mock using mocha, webpack, and typescript. I'm using all the plugins called out in the readme, but ended up getting the "cannot read property call of undefined" error mentioned in the readme. I tried the workaround of adding `import(rewiremock/webpack/interceptor)` mentioned in the readme. However, there seem to be a couple issues that have broken this workaround:

* the interceptor file has moved to `rewiremock/webpack/src/interceptor` from `rewiremock/webpack/interceptor/index.js`, meaning that import no longer resolves to a file that exists
* Typescript can't find anything exported at that path, meaning the module can't compile.

I've tried importing the new interceptor file directly with typescript and webpack, but can't seem to get this to work.

Any ideas?

**Comment by theKashey** [comment]
Thank you for noticing this, but importing `interceptor` is (shall be) no longer required, and I'll going to remove this moment from the readme.

What could be wrong:
- first - set your browser to stop on unhandled exceptions and check which file failed to be required (let's answer this question first).
- for example `rewiremock.proxy('file.js')` might generate this exception, if `file.js` is not present in the bundle.
- in this case just change API signature - `rewiremock.proxy(() => require('file.js'))`
