### ISSUE TITLE
Not getting any results at all using mocha/node

### ISSUE THREAD

**Issue by bwillem** [theKashey/rewiremock#97]
Mocking seems to not do anything. The node runtime still looks for the dependency from the project's node_modules directory, and ignores the stub.

```
// Component.js
import dependency from "dependency-in-node-modules"

export default () => {
  dependecy.method();
 
  return <div />;
}

```

```
// component.test.js
import Component from "../Component"
import render from "react-native-testing-library

rewiremock("dependency-in-node-modules").with(() => null);
rewiremock.enable();

render(<Component  />);
```

Runtime is still looking here: /project/node_modules/dependency-in-node-modules/

**Comment by theKashey** [comment]
That's how it should work - __you've already imported__ `Component` and nothing could change it.

There are two ways to fix:
1. Require it later
```diff
// component.test.js
-import Component from "../Component"
import render from "react-native-testing-library

rewiremock("dependency-in-node-modules").with(() => null);
rewiremock.enable();
+const Component = require("../Component"); // require when rewiremock is active
render(<Component  />);
```

2. Use babel plugin (see readme section about it)
```diff
// component.test.js
+ import rewiremock from 'rewiremock'; // should be imported "above" Component

import Component from "../Component"
import render from "react-native-testing-library

rewiremock("dependency-in-node-modules").with(() => null);
- rewiremock.enable(); no need to enable it

render(<Component  />);
```

**Comment by unicornware** [comment]
having the same issue in a typescript x mocha project. even when using the `rewiremock/babel` plugin.

**Comment by theKashey** [comment]
@unicornware - any chance to provide an example I can fix?

**Comment by unicornware** [comment]
@theKashey i would, but i already removed `rewiremock` from my project and don't have the bandwidth to do a re-drop and repro at the moment. if i get a chance, i'll open a new issue
